
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BD2FA8CE1F1AA849592D7A99794D136F'
    
_lr_action_items = {'LPAREN':([0,1,2,3,4,5,6,7,8,9,],[1,1,-1,1,1,1,-5,-4,-2,-3,]),'$end':([2,3,6,7,8,9,],[-1,0,-5,-4,-2,-3,]),'ALPHA':([0,1,2,3,4,5,6,7,8,9,],[2,2,-1,2,2,2,-5,-4,-2,2,]),'STAR':([2,3,4,6,7,8,9,],[-1,6,6,-5,6,-2,6,]),'ALTER':([2,3,4,6,7,8,9,],[-1,5,5,-5,-4,-2,-3,]),'RPAREN':([2,4,6,7,8,9,],[-1,8,-5,-4,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,3,4,5,7,9,],[3,4,7,7,9,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ALPHA','expression',1,'p_expression_alpha','automata2.py',151),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','automata2.py',156),
  ('expression -> expression ALTER expression','expression',3,'p_expression_alter','automata2.py',161),
  ('expression -> expression expression','expression',2,'p_expression_concat','automata2.py',166),
  ('expression -> expression STAR','expression',2,'p_expression_star','automata2.py',171),
]
